platform: x64
install:
  - git submodule update --init --recursive
  - ps: Install-Product node 4
  - npm -g install npm@next
  - npm install

test_script:
  - npm test

configuration:
  - Release

build: off
